// Storyboard cropping for the 60s pipeline — slice ONE 16-panel master sheet
// (a row-major 4×4 grid) into four per-segment shot guides, then RE-TILE each
// row's four panels into a 2×2 block before it goes to the video provider.
//
// Why 2×2 and not a 1×4 strip: BytePlus `CreateAsset` (the face-asset path every
// person-bearing reference must take, or Seedance's privacy filter rejects it)
// requires aspect ratio 0.4–2.5 and height 300–6000px. A 1×4 row is ~7:1 →
// rejected (`AspectRatioTooLarge`). Re-tiling a row's four panels into a 2×2
// (TL=1, TR=2, BL=3, BR=4) yields ~1.8:1 — well inside the limits — while keeping
// the four CONSECUTIVE panels of that segment, in order. The master still renders
// row-major (which it does well); only the crop step rearranges.
//
// The master is generated by gpt-image-2, so the grid is NOT pixel-exact (panel
// gutters + the burned-in badges/caption bars drift a few px). Each panel is
// extracted with a small INSET to stay clear of the neighbour's bleed — the
// guide only DIRECTS the video (the video prompt's leak-guard suppresses any
// residual badge/caption text), so a slightly tighter panel is safe.
//
// Pure bytes-in / bytes-out (no DB, no storage) — the orchestrator owns
// persistence. Mirrors the shape of lib/video/merge.ts.

import sharp from "sharp";
import { createLogger } from "../log.js";

const log = createLogger("crop");

/**
 * Fraction of a panel trimmed off each edge before re-tiling, to avoid bleeding
 * the adjacent panel's gutter / caption bar into the cell. Small — just enough to
 * absorb the model's grid drift.
 */
const PANEL_INSET_FRACTION = 0.02;

/**
 * Minimum output height (px) for any crop sent to the video provider. BytePlus
 * `CreateAsset` rejects images shorter than 300px; a 2×2 of two ~288px rows is
 * ~552px so it already clears the floor, but anchors (a single panel) need the
 * upscale. 512 keeps a comfortable margin under the 6000px ceiling.
 */
const MIN_OUTPUT_HEIGHT = 512;

/**
 * Directional trims for `cleanSheet2x2` — how much of each panel to shave off
 * before re-tiling, to remove the burned-in storyboard annotations. The scene
 * badge sits in a TOP corner and the caption bar is a thin strip along the
 * BOTTOM of every panel, so trimming those strips drops both. Kept modest so a
 * head/product near the panel edge is not clipped — TUNABLE after a visual pass.
 */
const TOP_TRIM_FRACTION = 0.14; // removes the top-corner scene-number badge
const BOTTOM_TRIM_FRACTION = 0.14; // removes the bottom caption bar

/** Read + validate the master's pixel dimensions. */
async function masterDims(
  bytes: Uint8Array,
): Promise<{ width: number; height: number }> {
  const meta = await sharp(Buffer.from(bytes)).metadata();
  const width = meta.width ?? 0;
  const height = meta.height ?? 0;
  if (!width || !height) {
    throw new Error("crop: could not read master image dimensions");
  }
  return { width, height };
}

/** Extract one grid cell `(row, col)` of a `rows×cols` master, inset on all sides. */
async function extractCell(
  bytes: Uint8Array,
  row: number,
  col: number,
  rows: number,
  cols: number,
  width: number,
  height: number,
): Promise<{ buf: Buffer; w: number; h: number }> {
  const cellW = Math.floor(width / cols);
  const cellH = Math.floor(height / rows);
  const insetX = Math.round(cellW * PANEL_INSET_FRACTION);
  const insetY = Math.round(cellH * PANEL_INSET_FRACTION);
  const left = col * cellW + insetX;
  const top = row * cellH + insetY;
  const w = Math.max(1, cellW - 2 * insetX);
  const h = Math.max(1, cellH - 2 * insetY);
  const buf = await sharp(Buffer.from(bytes))
    .extract({ left, top, width: w, height: h })
    .toBuffer();
  return { buf, w, h };
}

/**
 * Crop a row-major `rowCount`×4 master into one **2×2 block per row**. For row
 * `i` the four panels `4i+1 … 4i+4` are re-tiled TL→TR→BL→BR, so the block reads
 * in the same order (panel 1 top-left … panel 4 bottom-right). Returns one PNG
 * per row in reading order (row 0 first). Each block is ~1.8:1 and ≥300px tall —
 * inside BytePlus's asset limits.
 */
export async function cropRowsAs2x2(
  bytes: Uint8Array,
  rowCount: number,
): Promise<Uint8Array[]> {
  if (rowCount < 1) {
    throw new Error(`cropRowsAs2x2: rowCount must be ≥1, got ${rowCount}`);
  }
  const cols = 4;
  const { width, height } = await masterDims(bytes);

  const out: Uint8Array[] = [];
  for (let i = 0; i < rowCount; i++) {
    const panels = [];
    for (let j = 0; j < cols; j++) {
      panels.push(
        await extractCell(bytes, i, j, rowCount, cols, width, height),
      );
    }
    const pw = panels[0].w;
    const ph = panels[0].h;
    // Composite the four panels into a 2×2 canvas (panels touch edge-to-edge).
    const block = await sharp({
      create: {
        width: pw * 2,
        height: ph * 2,
        channels: 3,
        background: { r: 0, g: 0, b: 0 },
      },
    })
      .composite([
        { input: panels[0].buf, left: 0, top: 0 },
        { input: panels[1].buf, left: pw, top: 0 },
        { input: panels[2].buf, left: 0, top: ph },
        { input: panels[3].buf, left: pw, top: ph },
      ])
      .png()
      .toBuffer();

    // Upscale only if the block is somehow below the provider's height floor.
    let pipeline = sharp(block);
    if (ph * 2 < MIN_OUTPUT_HEIGHT) {
      pipeline = pipeline.resize({ height: MIN_OUTPUT_HEIGHT });
    }
    out.push(new Uint8Array(await pipeline.png().toBuffer()));
  }

  log.debug("✓ re-tiled master rows into 2×2 blocks", {
    rowCount,
    source: `${width}x${height}`,
    block: `${out.length ? "~" : ""}${Math.floor(width / cols) * 2}x${Math.floor(height / rowCount) * 2}`,
  });
  return out;
}

/**
 * Extract one cell `(row, col)` of a 2×2 sheet with a DIRECTIONAL trim: shave the
 * top strip (badge), the bottom strip (caption bar) and a small side inset
 * (gutter). Leaves the panel's photographic core.
 */
async function extractPanelClean(
  bytes: Uint8Array,
  row: number,
  col: number,
  width: number,
  height: number,
): Promise<{ buf: Buffer; w: number; h: number }> {
  const cellW = Math.floor(width / 2);
  const cellH = Math.floor(height / 2);
  const insetX = Math.round(cellW * PANEL_INSET_FRACTION);
  const trimTop = Math.round(cellH * TOP_TRIM_FRACTION);
  const trimBottom = Math.round(cellH * BOTTOM_TRIM_FRACTION);
  const left = col * cellW + insetX;
  const top = row * cellH + trimTop;
  const w = Math.max(1, cellW - 2 * insetX);
  const h = Math.max(1, cellH - trimTop - trimBottom);
  const buf = await sharp(Buffer.from(bytes))
    .extract({ left, top, width: w, height: h })
    .toBuffer();
  return { buf, w, h };
}

/**
 * Row-major grid a template storyboard of `n` beat panels is rendered in — the
 * SAME layout the storyboard prompt describes and `cleanSheetGrid` crops. A
 * near-square grid so each panel stays close to the output frame's shape. `n=4`
 * is `2×2` (identical to the legacy sheet); `n=3`/`n=5` leave one trailing cell
 * empty. Only used for template runs (`n` = template video-slot count, 2..6).
 */
export function panelGrid(n: number): { rows: number; cols: number } {
  if (n <= 1) return { rows: 1, cols: 1 };
  const cols = Math.ceil(Math.sqrt(n));
  const rows = Math.ceil(n / cols);
  return { rows, cols };
}

/** Extract cell `(row, col)` of a `rows×cols` sheet with the badge/caption trims. */
async function extractPanelCleanGrid(
  bytes: Uint8Array,
  row: number,
  col: number,
  rows: number,
  cols: number,
  width: number,
  height: number,
): Promise<{ buf: Buffer; w: number; h: number }> {
  const cellW = Math.floor(width / cols);
  const cellH = Math.floor(height / rows);
  const insetX = Math.round(cellW * PANEL_INSET_FRACTION);
  const trimTop = Math.round(cellH * TOP_TRIM_FRACTION);
  const trimBottom = Math.round(cellH * BOTTOM_TRIM_FRACTION);
  const left = col * cellW + insetX;
  const top = row * cellH + trimTop;
  const w = Math.max(1, cellW - 2 * insetX);
  const h = Math.max(1, cellH - trimTop - trimBottom);
  const buf = await sharp(Buffer.from(bytes))
    .extract({ left, top, width: w, height: h })
    .toBuffer();
  return { buf, w, h };
}

/**
 * The N-panel generalization of `cleanSheet2x2` for a template storyboard: trim
 * the first `n` panels of a `rows×cols` sheet clean of their badge + caption bar
 * and re-tile them, in row-major order, back into a `rows×cols` grid (any unused
 * trailing cell stays black). Same overall proportions and reading order as the
 * source, so it stays inside the provider's asset limits exactly like the 2×2.
 */
export async function cleanSheetGrid(
  bytes: Uint8Array,
  rows: number,
  cols: number,
  n: number,
): Promise<Uint8Array> {
  const { width, height } = await masterDims(bytes);
  const cells: { buf: Buffer; w: number; h: number }[] = [];
  for (let i = 0; i < n; i++) {
    cells.push(
      await extractPanelCleanGrid(
        bytes,
        Math.floor(i / cols),
        i % cols,
        rows,
        cols,
        width,
        height,
      ),
    );
  }
  const pw = cells[0].w;
  const ph = cells[0].h;
  const block = await sharp({
    create: {
      width: pw * cols,
      height: ph * rows,
      channels: 3,
      background: { r: 0, g: 0, b: 0 },
    },
  })
    .composite(
      cells.map((c, i) => ({
        input: c.buf,
        left: (i % cols) * pw,
        top: Math.floor(i / cols) * ph,
      })),
    )
    .png()
    .toBuffer();

  let pipeline = sharp(block);
  if (ph * rows < MIN_OUTPUT_HEIGHT) {
    pipeline = pipeline.resize({ height: MIN_OUTPUT_HEIGHT });
  }
  const cleaned = new Uint8Array(await pipeline.png().toBuffer());
  log.debug("✓ cleaned labelled N-panel sheet for the video model", {
    source: `${width}x${height}`,
    grid: `${rows}x${cols}`,
    n,
  });
  return cleaned;
}

/**
 * Turn ONE labelled 2×2 storyboard sheet into a CLEAN 2×2 for the video model:
 * each of the four panels is trimmed of its top-corner scene badge and bottom
 * caption bar, then the four are re-tiled edge-to-edge (TL=1, TR=2, BL=3, BR=4)
 * so no gridlines/badges/caption text remain to leak into the rendered clip. The
 * labelled sheet is unchanged; this is a provider-only copy. Pure bytes-in /
 * bytes-out (the caller owns storage). Reading order is preserved.
 */
export async function cleanSheet2x2(bytes: Uint8Array): Promise<Uint8Array> {
  const { width, height } = await masterDims(bytes);
  const panels = [
    await extractPanelClean(bytes, 0, 0, width, height),
    await extractPanelClean(bytes, 0, 1, width, height),
    await extractPanelClean(bytes, 1, 0, width, height),
    await extractPanelClean(bytes, 1, 1, width, height),
  ];
  const pw = panels[0].w;
  const ph = panels[0].h;
  const block = await sharp({
    create: {
      width: pw * 2,
      height: ph * 2,
      channels: 3,
      background: { r: 0, g: 0, b: 0 },
    },
  })
    .composite([
      { input: panels[0].buf, left: 0, top: 0 },
      { input: panels[1].buf, left: pw, top: 0 },
      { input: panels[2].buf, left: 0, top: ph },
      { input: panels[3].buf, left: pw, top: ph },
    ])
    .png()
    .toBuffer();

  let pipeline = sharp(block);
  if (ph * 2 < MIN_OUTPUT_HEIGHT) {
    pipeline = pipeline.resize({ height: MIN_OUTPUT_HEIGHT });
  }
  const cleaned = new Uint8Array(await pipeline.png().toBuffer());
  log.debug("✓ cleaned labelled 2×2 sheet for the video model", {
    source: `${width}x${height}`,
    panel: `${pw}x${ph}`,
  });
  return cleaned;
}
